In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import requests
from tqdm import tqdm

In [2]:
file_path = "/content/drive/MyDrive/FYP/IRP/Data/Acute_Oral_Toxicity/Acute_Oral_Toxicity.xlsx"

df = pd.read_excel(file_path)

# Check data and CASRN column
df.head(3)

,Formulation Name,Chemical Name,CASRN,DTXSID,Percent Active,Mixture,Data Type,Assay,Endpoint,Response Modifier,Response,Units,Species,Route,Sex,Reference,PMID,URL,Formulation ID,Record ID
0,NaN,1-Chloro-4-nitrobenzene,100-00-5,DTXSID5020281,NaN,N,In Vivo,Rat Acute Oral Toxicity,LD50,,294.0,mg/kg,Rat,Oral,Male,NLM Hazardous Substances Data Bank (undated),NaN,https://pubchem.ncbi.nlm.nih.gov/,NaN,AcuteOralToxicity_1
1,NaN,1-Chloro-4-nitrobenzene,100-00-5,DTXSID5020281,NaN,N,In Vivo,Rat Acute Oral Toxicity,LD50,,420.0,mg/kg,Rat,Oral,NaN,NLM Hazardous Substances Data Bank (undated),NaN,https://pubchem.ncbi.nlm.nih.gov/,NaN,AcuteOralToxicity_2
2,NaN,1-Chloro-4-nitrobenzene,100-00-5,DTXSID5020281,NaN,N,In Vivo,Rat Acute Oral Toxicity,LD50,,500.0,mg/kg,Rat,Oral,Male,NLM Hazardous Substances Data Bank (undated),NaN,https://pubchem.ncbi.nlm.nih.gov/,NaN,AcuteOralToxicity_3

In [4]:
print("Chemical Names count: ",len((df['Chemical Name'].unique())))
print("Unique CASRN count: ",len((df['CASRN'].unique())))
print("Total CASRN count:", len(df['CASRN']))
print("Total records:", len(df))

Chemical Names count:  9140
Unique CASRN count:  9124
Total CASRN count: 16839
Total records: 16839

In [ ]:
# Define helper function to get SMILES from PubChem
def get_smiles_from_cas(casrn):
    """
    Given a CASRN (CAS Registry Number), return the corresponding SMILES string
    using the PubChem REST API.
    """
    if pd.isna(casrn):
        return None

    url = f"https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/name/{casrn}/property/CanonicalSMILES/TXT"
    try:
        response = requests.get(url, timeout=10)
        if response.status_code == 200:
            smiles = response.text.strip()
            # Sometimes PubChem returns multiple lines; get only first valid SMILES
            return smiles.split("\n")[0]
        else:
            return None
    except Exception as e:
        print(f"Error fetching SMILES for {casrn}: {e}")
        return None

# Apply function to CASRN column

# Add progress bar
tqdm.pandas()

# If the CASRN column name has spaces or different casing, adjust here
df['SMILES'] = df['CASRN'].progress_apply(get_smiles_from_cas)

In [ ]:
# Save results
output_path = "/content/drive/MyDrive/FYP/IRP/Data/Acute_Oral_Toxicity/Acute_Oral_Toxicity_with_SMILES.csv"
df.to_csv(output_path, index=False)

print(f"Done! File saved at: {output_path}")
df[['CASRN', 'SMILES']].head(10)

In [ ]:
df.head()

,Formulation Name,Chemical Name,CASRN,DTXSID,Percent Active,Mixture,Data Type,Assay,Endpoint,Response Modifier,...,Units,Species,Route,Sex,Reference,PMID,URL,Formulation ID,Record ID,SMILES
0,NaN,1-Chloro-4-nitrobenzene,100-00-5,DTXSID5020281,NaN,N,In Vivo,Rat Acute Oral Toxicity,LD50,,...,mg/kg,Rat,Oral,Male,NLM Hazardous Substances Data Bank (undated),NaN,https://pubchem.ncbi.nlm.nih.gov/,NaN,AcuteOralToxicity_1,C1=CC(=CC=C1[N+](=O)[O-])Cl
1,NaN,1-Chloro-4-nitrobenzene,100-00-5,DTXSID5020281,NaN,N,In Vivo,Rat Acute Oral Toxicity,LD50,,...,mg/kg,Rat,Oral,NaN,NLM Hazardous Substances Data Bank (undated),NaN,https://pubchem.ncbi.nlm.nih.gov/,NaN,AcuteOralToxicity_2,C1=CC(=CC=C1[N+](=O)[O-])Cl
2,NaN,1-Chloro-4-nitrobenzene,100-00-5,DTXSID5020281,NaN,N,In Vivo,Rat Acute Oral Toxicity,LD50,,...,mg/kg,Rat,Oral,Male,NLM Hazardous Substances Data Bank (undated),NaN,https://pubchem.ncbi.nlm.nih.gov/,NaN,AcuteOralToxicity_3,C1=CC(=CC=C1[N+](=O)[O-])Cl
3,NaN,1-Chloro-4-nitrobenzene,100-00-5,DTXSID5020281,NaN,N,In Vivo,Rat Acute Oral Toxicity,LD50,,...,mg/kg,Rat,Oral,NaN,NLM Hazardous Substances Data Bank (undated),NaN,https://pubchem.ncbi.nlm.nih.gov/,NaN,AcuteOralToxicity_4,C1=CC(=CC=C1[N+](=O)[O-])Cl
4,NaN,1-Chloro-4-nitrobenzene,100-00-5,DTXSID5020281,NaN,N,In Vivo,Rat Acute Oral Toxicity,LD50,,...,mg/kg,Rat,Oral,Female,NLM Hazardous Substances Data Bank (undated),NaN,https://pubchem.ncbi.nlm.nih.gov/,NaN,AcuteOralToxicity_5,C1=CC(=CC=C1[N+](=O)[O-])Cl

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16839 entries, 0 to 16838
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Formulation Name   4659 non-null   object
 1   Chemical Name      16835 non-null  object
 2   CASRN              16839 non-null  object
 3   DTXSID             16187 non-null  object
 4   Percent Active     4559 non-null   float64
 5   Mixture            16839 non-null  object
 6   Data Type          16839 non-null  object
 7   Assay              16839 non-null  object
 8   Endpoint           16839 non-null  object
 9   Response Modifier  15180 non-null  object
 10  Response           16703 non-null  float64
 11  Units              13624 non-null  object
 12  Species            16616 non-null  object
 13  Route              16839 non-null  object
 14  Sex                5010 non-null   object
 15  Reference          11634 non-null  object
 16  PMID               0 non-null      float64
 17  URL                6635 non-null   object
 18  Formulation ID     4659 non-null   object
 19  Record ID          16839 non-null  object
 20  SMILES             16621 non-null  object
dtypes: float64(3), object(18)
memory usage: 2.7+ MB

In [ ]:
df.shape[0]

16839